FROM node:14-alpine

RUN mkdir -p /home/node/app && chown node:node -R /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node package*.json ./
USER node
RUN npm install
COPY --chown=node:node . .
EXPOSE 3000

CMD ["npm", "start"]