version: "3.8"

services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data:
  caddy-config: